spring:
  application:
    name: spring-sso-google
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 255283426159-gk7o4sr2mukqa9820bmadecgk1n1gnh2.apps.googleusercontent.com
            clientSecret: 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



server:
  port: 9191