spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: test-service
          uri:
            lb://test-service
          predicates:
          - Path=/test/**
server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}