package com.stream.mapExample;

import java.util.Arrays;
import java.util.List;

public class FlatMapExample {
	public static void main(String[] args) {
		List<List<Integer>> number = Arrays.asList(Arrays.asList(1, 2), Arrays.asList(3, 4), Arrays.asList(5, 6),
				Arrays.asList(7, 8), Arrays.asList(9, 10));
		System.out.println("List of Lists: "+number);
		//Flattern this list
		List<Integer> list = number.stream().flatMap(str->str.stream()).toList();
		System.out.println("List generated by flatmap: "+list);
	}
}
