server:
  port: 9191

spring:
  datasource:
    url: jdbc:h2:C:/data/cbdb
    driver-class-name: org.h2.Driver
    username: sailendra131
    password: 
  h2:
    console:
      enabled: true
      path: /h2-ui